// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjbdoVo8cJL2IgKrpXyWC31kRjvQGdcXk',
    appId: '1:496184354573:web:4119614636cd561f1fb244',
    messagingSenderId: '496184354573',
    projectId: 'quran-ab19e',
    authDomain: 'quran-ab19e.firebaseapp.com',
    storageBucket: 'quran-ab19e.firebasestorage.app',
    measurementId: 'G-9CLLZNJRL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7jsOP-GkGCUtkMbDCTFvgLtbm9FgoeBY',
    appId: '1:496184354573:android:030ddb26e81d1e361fb244',
    messagingSenderId: '496184354573',
    projectId: 'quran-ab19e',
    storageBucket: 'quran-ab19e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9IaefipsAY5EVx9cbsLOtRgmqYS1aePI',
    appId: '1:496184354573:ios:7bb25cfad64334451fb244',
    messagingSenderId: '496184354573',
    projectId: 'quran-ab19e',
    storageBucket: 'quran-ab19e.firebasestorage.app',
    iosBundleId: 'com.example.quranApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9IaefipsAY5EVx9cbsLOtRgmqYS1aePI',
    appId: '1:496184354573:ios:7bb25cfad64334451fb244',
    messagingSenderId: '496184354573',
    projectId: 'quran-ab19e',
    storageBucket: 'quran-ab19e.firebasestorage.app',
    iosBundleId: 'com.example.quranApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjbdoVo8cJL2IgKrpXyWC31kRjvQGdcXk',
    appId: '1:496184354573:web:00745c53a8bf86a51fb244',
    messagingSenderId: '496184354573',
    projectId: 'quran-ab19e',
    authDomain: 'quran-ab19e.firebaseapp.com',
    storageBucket: 'quran-ab19e.firebasestorage.app',
    measurementId: 'G-3P548CSNT6',
  );
}
